### ISSUE TITLE
List of Sessions Needed ASAP

### ISSUE THREAD

**Issue by bsstahl** [Microsoft/VisualStudio2019Launch#2]
I know the actual presentation decks will be here "...as soon as they become available..." but it would help to have at least a list of what the talks will be ASAP. That way, we can start planning the local events with regard to who will be delivering what talks.

**Comment by BethMassi** [comment]
Totally understand. We're working on the content now and will update the website with agenda and topics soon so keep an eye on that. Thanks for supporting a local event!

**Comment by onnov72** [comment]
@bsstahl A blog post has been published with a list of sessions and speakers [https://devblogs.microsoft.com/visualstudio/visual-studio-2019-launch-event-agenda-and-speakers-now-published/](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-launch-event-agenda-and-speakers-now-published/)

**Comment by bsstahl** [comment]
Interesting. That is helpful.  A bit more information would also be helpful, like: what is the session "Streamline your dream dev team" about? Is that a devops thing? What does it mean that the break at 19:30 UTC is "AI Infused"? Most of the rest is at least informative enough that we can get started planning whether or not we will do that session and if so, who should deliver it.  

Thanks for posting the link.

**Comment by webdr1** [comment]
Microsoft is who is stating launch date Aprdr4il 21st for https:/'/;surfslide.com I originally started this
application to have all search engines in one place have changed it to https:/;/surfsup.com/ Thanks for your help!

**Comment by webdr1** [comment]
A surfer app with tidal conditions preforcast for at surf beaches of interest  and have sales percentage
from all surf apparel and products as well as events local surf shop info anywhere in the world
