### ISSUE TITLE
Local event on April 20 in Suzhou has no register link but an advertisement

### ISSUE THREAD

**Issue by KexyBiscuit** [Microsoft/VisualStudio2019Launch#3]
[Local event on April 20 in Suzhou](https://visualstudio.microsoft.com/vs2019-launch/local-events/) has an "Register Here" link pointed to an advertisement, please fix that.

**Comment by BethMassi** [comment]
Thanks for the heads up. I'll email the organizer.

**Comment by webdr1** [comment]
Thank for the warning!

**Comment by KexyBiscuit** [comment]
The page is gone, closing.
