### ISSUE TITLE
Artwork date is different from our local event date.

### ISSUE THREAD

**Issue by hiroyukimori** [Microsoft/VisualStudio2019Launch#4]
I would like to use the artwork in this repository at our local event registration site.
However, the date on the artwork is different for local events. 
Can I change the date and use it?

**Comment by bsstahl** [comment]
The license file in the Repo says everything is under an MIT license which means we are free to modify and distribute as we see fit.

**Comment by BethMassi** [comment]
Yes! Per the readme.md you can absolutely do this.

**Comment by hiroyukimori** [comment]
Great!
Thanks for the information.
I'll try.
