### ISSUE TITLE
Link about China,Beijing

### ISSUE THREAD

**Issue by tai-yi** [Microsoft/VisualStudio2019Launch#7]
## Confused!

**Is there anything about VisualStudio 2019 event?**

![image](https://user-images.githubusercontent.com/26475230/55327407-a4624800-54bc-11e9-81f1-a381248bbedc.png)
![image](https://user-images.githubusercontent.com/26475230/55327455-b8a64500-54bc-11e9-9326-15efd6aefd5d.png)

**Comment by BethMassi** [comment]
Thanks for the heads up. We'll contact the organizer
